apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-personalise
          image: docker.io/glocker1v4/backend-personalise:v3
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: APP_WEB_URL
              value: "https://frontend-personalise-personalise.apps.cluster-2q2cx.2q2cx.sandbox2016.opentlc.com"
            - name: DB_HOST
              value: "db-service.personalise.svc.cluster.local"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: mysql-users-secret
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: DB_PASS
                  name: mysql-users-secret
